### ISSUE TITLE
all i can see is zeros.  no profit loss or price

### ISSUE THREAD

**Issue by shyambandla** [elsewhat/nft-profit-loss#31]
![image](https://user-images.githubusercontent.com/27348544/147124356-000fc585-b9d5-4780-bd16-f7f75edfe835.png)

**Comment by elsewhat** [comment]
Hi @shyambandla 

The repo uses opensea as the main source for trades. 

Since opensea is not able to capture the buy and sell transactions for cryptopunks, they do not show up in the report either.
You can see https://opensea.io/assets/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/9083 has no buy or sales transaction captured.

Suspect the same maybe for the other nfts as well.

**Comment by shyambandla** [comment]
thank you
